# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildTestDeploy
  steps:
  - script: echo Build step - Replace with actual build commands
    displayName: 'Build Application'
    
  - script: echo Run tests - Replace with actual test commands
    displayName: 'Run Tests'

  - script: echo Deploy to staging - Replace with actual deploy commands
    displayName: 'Deploy to Staging'

