# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    - script: dotnet build --configuration Release
      displayName: 'Build the application'

- stage: Test
  jobs:
  - job: Test
    dependsOn: Build
    steps:
    - script: dotnet test --configuration Release
      displayName: 'Run unit tests'

- stage: Deploy
  jobs:
  - job: Deploy
    dependsOn: Test
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '<YourAzureSubscription>'
        appType: 'webApp'
        WebAppName: '<YourWebAppName>'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'


